"""
This code tests the PuzzleMaker class.
"""

# Test imports.
import config
from puzzle_maker import PuzzleMaker
from word_arbiter import WordArbiter

##############
# MAIN CLASS #
##############

def test_generated_polygon():
    """ Test that the polygon generated by the PuzzleMaker class fulfils our
    requirements consistently. """
    maker = PuzzleMaker()
    arbiter = WordArbiter()
    iterations = 10
    for _ in range(iterations):
        polygon = maker.make_polygon()
        assert len(polygon.max_letter_word) == config.MAX_WORD_LENGTH
        assert arbiter.is_a_word(polygon.max_letter_word)
        assert len(polygon.other_words) >= config.MIN_OTHER_WORDS
